server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: google_route
          uri: https://example.org
          predicates:
            - Path=/google
          filters:
            - RedirectTo=302, https://google.com