server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
